# Day 1

In [24]:
# PyTorch와 NumPy 불러오기
import torch
import numpy as np

### Tensor 생성

In [25]:
# Tensor Node 생성
v = [3,4,5]

t1 = torch.IntTensor(v)
t1

tensor([3, 4, 5], dtype=torch.int32)

In [26]:
t2 = torch.LongTensor(v)
t2

tensor([3, 4, 5])

In [27]:
m = [ [3,4,5], [7,8,9]]
t3 = torch.FloatTensor(m)
t3

tensor([[3., 4., 5.],
        [7., 8., 9.]])

In [28]:
t4 = torch.DoubleTensor(m)
t4

tensor([[3., 4., 5.],
        [7., 8., 9.]], dtype=torch.float64)

In [29]:
t5 = torch.tensor([1,2,3], dtype=torch.int32)
t5

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
t6 = torch.tensor(20)
t6

tensor(20)

In [ ]:
t5.numpy()

20

In [32]:
t6.item() # scalar 값

20

In [ ]:
# nparray를 tensor 객체로 만들기
arr = np.array([1, 2, 3, 4], dtype=np.int32)
t7 = torch.from_numpy(arr)
t7

tensor([1, 2, 3, 4], dtype=torch.int32)

In [38]:
# torchvision (2차원 이상만 가능)
from torchvision import transforms
arr = np.array([[1,2],[3,4]])
transforms = transforms.ToTensor()
print(type(transforms))
t8 = transforms(arr)
t8

<class 'torchvision.transforms.transforms.ToTensor'>


tensor([[[1, 2],
         [3, 4]]], dtype=torch.int32)

In [42]:
from PIL import Image
from torchvision import transforms

arr = np.array([[0,128,255],[64,192,32]], dtype=np.uint8)
image = Image.fromarray(arr)
print(type(image))
transforms = transforms.ToTensor()
t9 = transforms(image)
t9

<class 'PIL.Image.Image'>


tensor([[[0.0000, 0.5020, 1.0000],
         [0.2510, 0.7529, 0.1255]]])

### Operation

In [ ]:
# operation node 생성 : torch 연산함수 사용
a = torch.tensor(5)
b = torch.IntTensor([1,2,3])

In [ ]:
# a + b
# element wise
# [5,5,5] + [1,2,3]
c = torch.add(a, b) # a+b, a.add(b)와 같음
c

tensor([6, 7, 8], dtype=torch.int32)

In [ ]:
# broad casting
d = torch.IntTensor([1,2,3])
e = torch.IntTensor([[1,2,3], [4,5,6]])
f = d + e
f

tensor([[2, 4, 6],
        [5, 7, 9]], dtype=torch.int32)

In [ ]:
# a - b
# [5,5,5] - [1,2,3]
torch.sub(a, b)

tensor([4, 3, 2], dtype=torch.int32)

In [ ]:
# a * b
# [5,5,5] * [1,2,3]
torch.mul(a, b)

tensor([ 5, 10, 15], dtype=torch.int32)

In [52]:
# b ** 2
# [1^2, 2^2, 3^2]
torch.square(b)

tensor([1, 4, 9], dtype=torch.int32)

### 행렬 곱 (Matrix Multiplication)

In [ ]:
f = torch.IntTensor([[1,2], [3,4]])
g = torch.IntTensor([[5,6], [7,8]])
h = torch.mul(f, g) # f * g
i = torch.matmul(f, g) # 행렬끼리만
print(h)
print(i)

tensor([[ 5, 12],
        [21, 32]], dtype=torch.int32)
tensor([[19, 22],
        [43, 50]], dtype=torch.int32)


### 통계 함수

In [57]:
j = torch.FloatTensor([[1,2,3,4,5]])
j

tensor([[1., 2., 3., 4., 5.]])

In [ ]:
torch.mean(j) # j.mean()과 같음

tensor(3.)

In [60]:
torch.sum(j)

tensor(15.)

In [62]:
k = torch.FloatTensor([[1,2], [3,4]])

In [63]:
torch.mean(k)

tensor(2.5000)

In [ ]:
# torch.mean(k, dim=0)
# dim=0 : 각 col의 평균
k.mean(dim=0)

tensor([2., 3.])

In [67]:
# dim=1 : 각 row의 평균
k.mean(dim=1)

tensor([1.5000, 3.5000])

In [ ]:
# 최대값
k.max()

tensor(4.)

In [ ]:
# col별 최대값과 그의 인덱스
v, i = k.max(dim=0)
print(v)
print(i)

tensor([3., 4.])
tensor([1, 1])


In [73]:
# row별 최대값과 그의 인덱스
v, i = k.max(dim=1)
print(v)
print(i)

tensor([2., 4.])
tensor([1, 1])


### 인덱싱 슬라이싱
- 인덱스번호 : 0부터 시작, 마지막은 -1
- 슬라이싱 : [시작:끝(포함X):증가치]

In [74]:
m = torch.IntTensor([11,22,33,44,55])
m

tensor([11, 22, 33, 44, 55], dtype=torch.int32)

In [78]:
m[0].item()

11

In [79]:
m[-1].item()

55

In [86]:
m[1:4:1]

tensor([22, 33, 44], dtype=torch.int32)

In [87]:
m[2:]

tensor([33, 44, 55], dtype=torch.int32)

### Cost와 미분