### Multiple Linear Regression - matmul (high level)

In [1]:
# 필요한 라이브러리 호출
import torch
import torch.nn.functional as F
from torch.nn import Linear, MSELoss, Sequential
from torch.optim import Adam
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
# test.csv 불러오기
df = pd.read_csv('data/test.csv', header=None)
df.columns = ['q1', 'q2', 'mid', 'final']
df.head()

q1  q2  mid  final
0  73  80   75    152
1  93  88   93    185
2  89  91   90    180
3  96  98  100    196
4  73  66   70    142

In [4]:
# row는 전체, col은 마지막만 추출
x_data = df.iloc[:, :-1].values
y_data = df.iloc[:, [-1]].values

In [5]:
# 텐서 노드 만들기 (w, b 정의 안 해도 됨)
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [8]:
# 학습
model = Sequential()
model.add_module('nn1', Linear(3, 1))
loss_fn = MSELoss()
optimizer = Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    hx = model(x)
    cost = loss_fn(hx, y)
    cost.backward()
    optimizer.step()
    print(f'{epoch} - cost : {cost.item()}')

0 - cost : 42131.5546875
1 - cost : 32732.64453125
2 - cost : 24559.080078125
3 - cost : 17622.52734375
4 - cost : 11918.9345703125
5 - cost : 7423.66064453125
6 - cost : 4086.19970703125
7 - cost : 1825.11083984375
8 - cost : 524.480712890625
9 - cost : 33.701255798339844
10 - cost : 172.4781036376953
11 - cost : 742.1539306640625
12 - cost : 1542.546142578125
13 - cost : 2391.156005859375
14 - cost : 3140.178955078125
15 - cost : 3687.294677734375
16 - cost : 3978.4970703125
17 - cost : 4003.807861328125
18 - cost : 3788.32470703125
19 - cost : 3381.316162109375
20 - cost : 2845.406982421875
21 - cost : 2247.08642578125
22 - cost : 1649.03369140625
23 - cost : 1104.3900146484375
24 - cost : 652.9058837890625
25 - cost : 318.8815612792969
26 - cost : 110.79158020019531
27 - cost : 22.47867202758789
28 - cost : 35.71919631958008
29 - cost : 123.8412094116211
30 - cost : 255.9461669921875
31 - cost : 401.186279296875
32 - cost : 532.5416870117188
33 - cost : 629.6361083984375
34 - cost 

In [11]:
# 학습된 weight 값 확인
model[0].weight

Parameter containing:
tensor([[0.3732, 0.5260, 1.1231]], requires_grad=True)

In [12]:
# 학습된 bias 값 확인
model[0].bias

Parameter containing:
tensor([-0.7036], requires_grad=True)

In [13]:
# 예측해보기 : q1 80점, q2 90, mid 90점인 경우의 최종 점수 예측하기
model(torch.FloatTensor([[90, 80, 80]]))

tensor([[164.8095]], grad_fn=<AddmmBackward>)