### XOR Problem (Sequential)

In [24]:
# 필요한 라이브러리 호출
import torch
from torch.optim import Adam
from torch.nn import Linear, MSELoss, Sigmoid, BCELoss, Sequential, Module, Softmax, CrossEntropyLoss
import torch.nn.functional as F
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split

In [25]:
# 데이터 준비 (x: input -XOR-> y: output)
x_data = [[0, 0], [0, 1], [1, 0], [1, 1]]
y_data = [[0], [1], [1], [0]]

In [26]:
# Tensor로 변환
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [46]:
# Training
model = Sequential()

model.add_module('nn1', Linear(2, 2)) # w: 2x2, b: 2
model.add_module('sig1', Sigmoid())

model.add_module('nn2', Linear(2, 1)) # w: 2x2, b: 1
model.add_module('sig2', Sigmoid())

loss_fn = BCELoss()
optimizer = Adam(model.parameters(), lr=0.1)

for epoch in range(1000):
    optimizer.zero_grad()
    hx = model(x) # z = matmul(x, w) + b, hx = sigmoid(z)
    cost = loss_fn(hx, y)
    cost.backward()
    optimizer.step()

    pred = (hx > 0.5) + 0

    print(f'{epoch} - cost : {cost.item()} | accuracy : {accuracy_score(y.numpy(), pred.numpy())}')

0 - cost : 0.6938578486442566 | accuracy : 0.5
1 - cost : 0.6965159773826599 | accuracy : 0.5
2 - cost : 0.6935980319976807 | accuracy : 0.5
3 - cost : 0.6936880350112915 | accuracy : 0.5
4 - cost : 0.6946909427642822 | accuracy : 0.5
5 - cost : 0.6939203143119812 | accuracy : 0.5
6 - cost : 0.6930285096168518 | accuracy : 0.5
7 - cost : 0.6931792497634888 | accuracy : 0.5
8 - cost : 0.693671464920044 | accuracy : 0.5
9 - cost : 0.6934887170791626 | accuracy : 0.5
10 - cost : 0.6928090453147888 | accuracy : 0.5
11 - cost : 0.6923584342002869 | accuracy : 0.75
12 - cost : 0.6923490166664124 | accuracy : 0.5
13 - cost : 0.6922229528427124 | accuracy : 0.5
14 - cost : 0.6915304064750671 | accuracy : 0.5
15 - cost : 0.690521776676178 | accuracy : 0.75
16 - cost : 0.689613938331604 | accuracy : 0.5
17 - cost : 0.6887446641921997 | accuracy : 0.5
18 - cost : 0.6874706745147705 | accuracy : 0.5
19 - cost : 0.6855757236480713 | accuracy : 0.5
20 - cost : 0.6832322478294373 | accuracy : 0.75
21

In [50]:
# 예측값
model(x)

tensor([[9.4191e-04],
        [9.9928e-01],
        [9.9927e-01],
        [6.5740e-04]], grad_fn=<SigmoidBackward>)

In [ ]:
model(x) > 0.5

tensor([[False],
        [ True],
        [ True],
        [False]])

In [48]:
z1 = model[0](x)
hx1 = model[1](z1)
z = model[2](hx1)
hx = model[3](z)
hx

tensor([[9.4191e-04],
        [9.9928e-01],
        [9.9927e-01],
        [6.5740e-04]], grad_fn=<SigmoidBackward>)

---

### XOR Problem (Class)

In [51]:
# 필요한 라이브러리 호출
import torch
from torch.optim import Adam
from torch.nn import Linear, Sigmoid, BCELoss, Module
from sklearn.metrics import accuracy_score

In [52]:
# 모델 정의
class XORModel(Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.nn1 = Linear(2, 100)
        self.sig1 = Sigmoid()
        self.nn2 = Linear(100, 1)
        self.sig2 = Sigmoid()
        
    def forward(self, x):
        z1 = self.nn1(x)
        hx1 = self.sig1(z1)
        z2 = self.nn2(hx1)
        hx2 = self.sig2(z2)
        return hx2

In [53]:
# 데이터 준비 (x: input -XOR-> y: output)
x_data = [[0, 0], [0, 1], [1, 0], [1, 1]]
y_data = [[0], [1], [1], [0]]

In [54]:
# Tensor로 변환
x = torch.FloatTensor(x_data)
y = torch.FloatTensor(y_data)

In [55]:
# 모델 초기화
model = XORModel()

In [56]:
# 손실 함수와 옵티마이저 정의
loss_fn = BCELoss()
optimizer = Adam(model.parameters(), lr=0.1)

In [57]:
# 학습
for epoch in range(1000):
    optimizer.zero_grad()

    hx = model(x)  # 순전파
    cost = loss_fn(hx, y) # 비용 계산
    cost.backward() # 역전파
    optimizer.step() # 가중치 업데이트
    pred = (hx > 0.5) + 0  # 예측 결과 0.5보다 크면 1, 그렇지 않으면 0
    accuracy = accuracy_score(y.numpy(), pred.numpy()) # 정확도 계산
    
    # 일정 간격으로 결과 출력
    if epoch % 100 == 0:
        print(f'Epoch [{epoch+1}/1000], Loss: {cost.item():.4f}, Accuracy: {accuracy:.4f}')

Epoch [1/1000], Loss: 0.7346, Accuracy: 0.5000
Epoch [101/1000], Loss: 0.0590, Accuracy: 1.0000
Epoch [201/1000], Loss: 0.0112, Accuracy: 1.0000
Epoch [301/1000], Loss: 0.0055, Accuracy: 1.0000
Epoch [401/1000], Loss: 0.0034, Accuracy: 1.0000
Epoch [501/1000], Loss: 0.0023, Accuracy: 1.0000
Epoch [601/1000], Loss: 0.0017, Accuracy: 1.0000
Epoch [701/1000], Loss: 0.0013, Accuracy: 1.0000
Epoch [801/1000], Loss: 0.0010, Accuracy: 1.0000
Epoch [901/1000], Loss: 0.0008, Accuracy: 1.0000


In [ ]:
# 최종 예측값
predictions = model(x)
print("Final Predictions: \n", (predictions > 0.5).float())

Final Predictions: 
 tensor([[0.],
        [1.],
        [1.],
        [0.]])
